"""fase 0 field assessment tables

Revision ID: 088e3e907642
Revises: a2b3c4d5e6f7
Create Date: 2026-09-14 18:02:05.626826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088e3e907642'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fema_table_6_6_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bands_json', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('linked_building_project_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.Enum('draft', 'safety_done', 'triage_done', 'archived', name='assessmentstage'), nullable=False),
    sa.Column('sync_status', sa.Enum('local_only', 'pending_sync', 'synced', name='syncstatus'), nullable=False),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_building_project_id'], ['building_projects.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_table('building_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('address_line', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('municipio_code', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('n_stories_above', sa.Integer(), nullable=True),
    sa.Column('n_stories_below', sa.Integer(), nullable=True),
    sa.Column('total_height_m', sa.Float(), nullable=True),
    sa.Column('plan_area_m2', sa.Float(), nullable=True),
    sa.Column('structural_system', sa.String(length=30), nullable=True),
    sa.Column('floor_system', sa.String(length=30), nullable=True),
    sa.Column('occupancy_use_nsr10', sa.String(length=4), nullable=True),
    sa.Column('has_asbuilt_docs', sa.Boolean(), nullable=False),
    sa.Column('has_geotech_hazard', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['field_assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('field_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('component_tag', sa.String(length=50), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['field_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('inspector_name', sa.String(length=255), nullable=True),
    sa.Column('inspector_id', sa.String(length=100), nullable=True),
    sa.Column('inspector_org', sa.String(length=255), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hazards_json', sa.JSON(), nullable=True),
    sa.Column('component_damage_json', sa.JSON(), nullable=True),
    sa.Column('access_condition_json', sa.JSON(), nullable=True),
    sa.Column('residual_drift_pct', sa.Float(), nullable=True),
    sa.Column('placard', sa.Enum('green', 'yellow', 'red', name='placard'), nullable=True),
    sa.Column('placard_reasons', sa.JSON(), nullable=True),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.Column('manual_override', sa.Enum('green', 'yellow', 'red', name='placard_override'), nullable=True),
    sa.Column('manual_override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['field_assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('triage_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('applicability_ok', sa.Boolean(), nullable=False),
    sa.Column('exceptional_flags_json', sa.JSON(), nullable=True),
    sa.Column('shortcut_applied', sa.String(length=30), nullable=True),
    sa.Column('stories_json', sa.JSON(), nullable=True),
    sa.Column('story_ratings_json', sa.JSON(), nullable=True),
    sa.Column('table_6_6_config_id', sa.String(length=36), nullable=True),
    sa.Column('building_rating', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('low_risk', 'asce41_candidate', 'high_risk', 'not_applicable', name='triagedecision'), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['field_assessments.id'], ),
    sa.ForeignKeyConstraint(['table_6_6_config_id'], ['fema_table_6_6_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_results')
    op.drop_table('safety_evaluations')
    op.drop_table('field_photos')
    op.drop_table('building_snapshots')
    op.drop_table('field_assessments')
    op.drop_table('fema_table_6_6_configs')
    # ### end Alembic commands ###
